default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Abhishek11@
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: demo_app_development

test:
  <<: *default
  database: demo_app_test

production:
  <<: *default
  database: demo_app_production
  username: demo_app
  password: <%= ENV['DEMO_APP_DATABASE_PASSWORD'] %>
